sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-1
    - secure: YJ5Nt+/iox51vQmpdaOH0SnIy1dN9wxeFK4GnFlfXODGp3ktwUFq+/0BF8nDNFEyzUgIG0qaCsgxR1BRRtgm/mEn7/6Py+xGuP/6lf/9ITdu5eFiLe+lQUFlzyKVJMdxsrLWjQZHBgSE+F62Hx2+6ulbvToOwmHJemrUoyVspQQ=
    - secure: eP//5fjwn70cgsZ0u62BHWV5hJo6PTfhE7PaGGRyqOWlmtK/z2xDnENhZ1Y9VO0oCYsH2jzrEtix/4/U85wWLapCcNW8eXs/PzSwGqm0qw3D/GeMkjt/eiCRuL/CzE0Fk+IRmnpw4Qa00fYOE8wuqySDlcRwUZsNFwD0VgO7pC0=

before_install:
  - pip install awscli

install:
  - pip install -r requires/testing.txt
  - python setup.py develop

stages:
  - test
  - name: upload_coverage
    if: branch = master
  - name: deploy
    if: tag IS present

script: nosetests

jobs:
  include:
    - stage: test
      services:
        - rabbitmq
      script: nosetests
      after_success:
        - aws cp .coverage "s3://com-gavinroy-travis/rejected/$TRAVIS_BUILD_NUMBER/.coverage.${TRAVIS_PYTHON_VERSION}"
    - stage: upload coverage
      python: 3.5
      script:
        - mkdir coverage
        - aws cp --recursive s3://com-gavinroy-travis/rejected/$TRAVIS_BUILD_NUMBER/ coverage
        - cd coverage
        - coverage combine
        - cd ..
        - mv coverage/.coverage .
        - coverage report
        - codecov
    - stage: deploy
      python: 3.5
      deploy:
        distributions: sdist bdist_wheel
        provider: pypi
        user: crad
        on:
          tags: true
          all_branches: true
        password:
          secure: QNndN99rD5boB/Sg3I0CzjkFUF1JmGrsQKZ7ONiA+obUWQDqOmggUoPEs1zN8xIExDcM4tPhlCQX0QiYJrKdLQwWiClvKo1wpYUxVm0s/W8SqvhV3IK9VxhMrbZUkmksO48TH4YKav06rEkVxke9g3U92XUJZ6cRAnYUKrjMYaQ=
